# Generated by Django 3.2.3 on 2022-02-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='HeraldSupportClan', max_length=255),
        ),
    ]
