# Generated by Django 3.2.3 on 2022-02-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0004_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
