# Generated by Django 3.2.3 on 2022-02-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='studentimage',
            field=models.ImageField(max_length=800, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='studentname',
            field=models.CharField(max_length=200),
        ),
    ]
