# Generated by Django 3.2.3 on 2022-02-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0009_question_respose'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
