# Generated by Django 3.2.3 on 2022-02-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0010_question_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respose',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HSC.respose'),
        ),
    ]
