# Generated by Django 3.2.3 on 2022-02-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0011_alter_respose_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventimg', models.ImageField(max_length=800, upload_to='events/')),
            ],
        ),
        migrations.AlterField(
            model_name='respose',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='HSC.question'),
        ),
    ]
