# Generated by Django 3.2.3 on 2022-02-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0012_auto_20220222_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutimage', models.ImageField(max_length=800, upload_to='eventsabout/')),
                ('aboutdesc', models.TextField(max_length=1000)),
                ('moredesc', models.TextField(max_length=500)),
            ],
        ),
    ]
