# Generated by Django 3.2.3 on 2022-02-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0013_eventabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentimage', models.ImageField(max_length=800, upload_to='eventstudentsreview/')),
                ('studentreview', models.TextField(max_length=800)),
                ('studentname', models.CharField(max_length=200)),
                ('studentcourse', models.CharField(max_length=200)),
            ],
        ),
    ]
