# Generated by Django 3.2.3 on 2022-02-25 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HSC', '0015_toppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='respose',
            name='likes',
            field=models.ManyToManyField(related_name='response', to=settings.AUTH_USER_MODEL),
        ),
    ]
