# Generated by Django 3.2.3 on 2022-03-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0017_review2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='respose',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='respose',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='respose',
            name='question',
        ),
        migrations.RemoveField(
            model_name='respose',
            name='user',
        ),
        migrations.DeleteModel(
            name='review2',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Respose',
        ),
    ]
