# Generated by Django 3.2.3 on 2022-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0022_auto_20220301_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='state',
            field=models.CharField(default='zero', max_length=40),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
