# Generated by Django 3.2.3 on 2022-03-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0023_auto_20220310_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallerytitle', models.CharField(max_length=255)),
                ('galleryimage', models.ImageField(max_length=800, upload_to='galleryimage/')),
            ],
        ),
    ]
