# Generated by Django 3.2.3 on 2022-04-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0024_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('description', models.TextField(default='description')),
            ],
            options={
                'verbose_name_plural': 'eventCategory',
            },
        ),
        migrations.CreateModel(
            name='EventGalleryPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventimage', models.ImageField(max_length=800, upload_to='eventgallery/')),
                ('eventCategory', models.ManyToManyField(to='HSC.EventGalleryCategory')),
            ],
        ),
    ]
