# Generated by Django 3.2.3 on 2022-04-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0025_eventgallerycategory_eventgallerypictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='studentimage',
        ),
    ]
