# Generated by Django 3.2.3 on 2022-04-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0027_review_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='student_image',
        ),
    ]
