# Generated by Django 3.2.3 on 2022-04-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0028_remove_review_student_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
