# Generated by Django 3.2.3 on 2022-04-14 02:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0030_studentreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='studentimage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[50, 80], upload_to='student'),
        ),
    ]
