# Generated by Django 3.2.3 on 2022-04-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0031_alter_studentreview_studentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='studentimage',
            field=models.ImageField(max_length=800, upload_to='events/'),
        ),
    ]
