# Generated by Django 3.2.3 on 2022-04-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0032_alter_studentreview_studentimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentreview',
        ),
    ]
