# Generated by Django 3.2.3 on 2022-04-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HSC', '0036_auto_20220416_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='HSC.reply'),
        ),
    ]
