# Generated by Django 3.2.3 on 2022-04-21 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HSC', '0039_auto_20220421_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='ready_by_Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HSC.author'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='ready_by_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
